package uk.al_richard.BloomSearch;

import java.util.ArrayList;
import java.util.List;

/*
 This code generated by CharGPT as an experiment.
 */
public class BalancedSequence {

    public static List<Integer> generateSequence(int n) {
        List<Integer> sequence = new ArrayList<>();
        int currentNumber = 0;
        for (int i = 0; i < n; i++) {
            while (!isBalanced(currentNumber)) {
                currentNumber++;
            }
            sequence.add(currentNumber);
            currentNumber++;
        }
        return sequence;
    }

    public static boolean isBalanced(int number) {
        String binary = Integer.toBinaryString(number);
        int ones = 0;
        int zeroes = 0;
        for (char c : binary.toCharArray()) {
            if (c == '1') {
                ones++;
            } else {
                zeroes++;
            }
        }
        return ones == zeroes;
    }

    public static void main(String[] args) {
        int n = 8;
        List<Integer> sequence = generateSequence(n);
        System.out.println("Sequence of " + n + " balanced integers: " + sequence);
    }
}

